version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
  indexer:
    build: ./indexer/
    container_name: indexer
    networks:
      - esnet
    depends_on:
      elasticsearch:
          condition: service_healthy
    entrypoint: ["python", "indexer.py"]
    volumes:
      - ./resources:/app/resources
  server:
    build: ./server/
    container_name: server
    networks:
      - esnet
    ports:
      - "4000:4000"
    depends_on:
      elasticsearch:
          condition: service_healthy
    entrypoint: ["python"]
    volumes:
      - ./resources:/app/resources
networks:
    esnet:
